Some addition and correction to the logic nodes docs
UPBGE/UPBGE-Docs pull request #49
Opened 2024-11-29 00:37 UTC by xavco63

2024-12-01 07:01 UTC, lordloki commented
@IzaZed , could you check these modifications?

2024-12-03 11:38 UTC, IzaZed requested changes

2024-12-03 11:38 UTC, IzaZed commented on source/manual/logic_nodes/input/gamepad/gamepad_vibrate.rst
> +   How many seconds the vibration have to play.
typo, should be "vibration has to"

2024-12-03 11:38 UTC, IzaZed commented on source/manual/logic_nodes/input/keyboard/keyboard_key.rst
> +   is activated while the key is pressed and ``Up`` is activated once the last frame the key is pressed.
Up activates on the frame after the key has been released

2024-12-03 11:38 UTC, IzaZed commented on source/manual/logic_nodes/input/mouse/mouse_status.rst
> +   The X movement of the cursor on the game window comparing to previous frame position.
typo, should be "compared"

2024-12-03 11:38 UTC, IzaZed commented on source/manual/logic_nodes/input/mouse/mouse_status.rst
> +   The Y movement of the cursor on the game window comparing to previous frame position.
typo, should be "compared"

2024-12-03 11:38 UTC, IzaZed commented on source/manual/logic_nodes/input/mouse/mouse_status.rst
> +   *1* if the wheel scroll up and *-1* if the wheel scroll down, *0* else.
*1* if the wheel is scrolled up and *-1* if the wheel is scrolled down, else *0*.

2024-12-03 20:16 UTC, IzaZed approved these changes

2024-12-03 20:28 UTC, merged